---
title: "Day 1 Task & Activities"
format: html
echo: FALSE 
editor: visual
---

## Data import and exploration

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv")) |>
  clean_names()# %>% or |>
#can also say janitor::clean_names() if janitor library is notloaded 
```
```{r}
rm(list = ls())
stl_lead <- read.csv(here::here("data", "stl_blood_lead.csv"))
  stl_lead <- stl_lead |>
  clean_names()

names(stl_lead)
```

```{r}
stl_lead_prop <- stl_lead |>
  mutate(prop_white = (white/total_pop)* 100)
dim(stl_lead_prop)
names(stl_lead_prop) #check for new variable name

```

```{r}
mutate(.data = stl_lead, prop_white = (white/total_pop)* 100)
```

## Visualized data
Creating a scatterplot of percentage of children in each census tract with elevated blood lead levels
```{r}
pop_elevated_plot <- ggplot(data = stl_lead_prop, aes(x = prop_white, y = pct_elevated)) +
  geom_jitter(color = "firebrick", shape = "diamond", size =2)+
  theme_minimal() +
  labs(title = "Children with elevated blood lead levels",
       x = "Percent of elevated lead levels",
       y = "Children with elevated blood levels",)
#save plot
ggsave(here::here("figs", "pop_elevated_plot.png"), height = 6, width = 7)
pop_elevated_plot
```

```{r}
pct_elevated_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(fill = "coral")+
  theme_minimal() +
  labs(title = "Elevated blood lead levels",
       x = "Percent of elevated lead levels")
#save plot
ggsave(here::here("figs", "pct_elevated_plot.png"), height = 6, width = 7)
pct_elevated_plot
```

